/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kursovaya;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jFrame2 = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jFrame3 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setTitle("Правила игры переставь фигуры");
        jFrame1.setBounds(new java.awt.Rectangle(0, 0, 450, 400));
        jFrame1.setLocation(new java.awt.Point(480, 240));

        jButton1.setText("Перейти к игре");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("                                   Добро пожаловать!\nПри нажатии кнопки \"\" перед вами появится игровое \nполе 3х3 с стоящими на нем фигурами.Ваша задача заключается \nв том,чтобы перенести верхние фигуры вниз,а верхние вверх,игра \nсчитается оконченной если переставлены все фигуры.Так же,в \nтаблице сбоку будут показываться ваши ходы.Желаю удачи!\n\n\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButton1)
                .addContainerGap(159, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame2.setTitle("Правила игры крестики-нолики");
        jFrame2.setBounds(new java.awt.Rectangle(0, 0, 450, 400));
        jFrame2.setLocation(new java.awt.Point(480, 240));

        jButton3.setText("Начать игру");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("                                    Добро пожаловать!\nПри нажатии кнопки \"Начать игру!\" перед вами появится поле 3х3\nдля игры в крестики-нолики.Ваша задача заключается в том,\nчтобы собрать в ряд Крестики(Нолики)Побидителем считается тот,\nкто соберет три Крестика(Нолика) в ряд по горизонтали,вертикали\nили диагонали.В табло сбоку будет отображаться счет игры.\nЖелаю удачи!");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton3)
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton3)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jFrame3.setTitle("Игра");
        jFrame3.setBounds(new java.awt.Rectangle(0, 0, 585, 420));
        jFrame3.setLocation(new java.awt.Point(480, 220));

        jTable1.setShowGrid(true);
        jTable1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 36)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null},
                {"2", null, null, null},
                {"3", null, null, null}
            },
            new String [] {
                "", "A", "B", "C"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(80);
        jTable1.setRowSelectionAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel1.setText("Игровое поле");

        jTable2.setShowGrid(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Фигура", "Клетка n-1", "Клетка n"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(70);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(60);
        }

        jLabel2.setText("Таблица ходов");

        jButton2.setText("Начать игру");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Переставь фигуры", jPanel1);

        jTable3.setShowGrid(true);
        jTable3.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setGridColor(new java.awt.Color(0, 0, 0));
        jTable3.setRowHeight(100);
        jTable3.setRowSelectionAllowed(false);
        jTable3.setSelectionBackground(new java.awt.Color(51, 102, 255));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable3MousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable3.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable3.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Крестики-нолики", jPanel2);

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Курсовая работа");
        setLocation(new java.awt.Point(480, 240));

        jMenu1.setText("Игры");

        jMenu2.setText("Об игре");

        jMenuItem2.setText("Переставь фигуры");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Крестики-нолики");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenu1.add(jMenu2);

        jMenuItem4.setText("Выход");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    jFrame1.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    jFrame2.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    jFrame3.setVisible(true);
    jFrame1.dispose();
    jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    jFrame3.setVisible(true);
    jFrame2.dispose();
    jTabbedPane1.setSelectedIndex(1);
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        
        // int row=jTable3.getSelectedRow();
         //int column=jTable3.getSelectedColumn();
         //jTable3.setValueAt("  "+"X", row, column);
           // player();      
            //comp();       
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MousePressed
   //крестики нолики 
   //player_move();      
    game();
   // comp_move();

    }//GEN-LAST:event_jTable3MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     StartField();
    }//GEN-LAST:event_jButton2ActionPerformed
    //int clickCounter=0;
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
    //clickCounter++;
    //game2();
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     //  clickCounter++;
      //  game2();
    
    }//GEN-LAST:event_jTable1MouseClicked
//boolean player=true;
int counter=0;
int compMove=0;

public void game(){ 
   String win = "";
   player_move(); 
   compMove++;
   
   if(compMove<=4){
       comp_move();
       System.out.println("GHB");
   }
   
   System.out.println("COMP="+compMove);
   System.out.println("counter="+counter);
   
   if(counter>5 ){
       win=checkWin();
       System.out.println("W="+win);
       
        if("  X".equals(win)){ 
           JOptionPane.showMessageDialog(null, "Выиграл человек!",null,0);
           
           for(int i=0;i<3;i++){
               for(int j=0;j<3;j++){
                   jTable3.setValueAt(null,i,j);
                   counter=0;
                   compMove=0;
                }
            }
        }
        else if("  O".equals(win)){
            JOptionPane.showMessageDialog(null, "Выиграл компьютер!\nПопробуйте еще раз!",null,0);
            
            for(int i=0;i<3;i++){
                for(int j=0;j<3;j++){
                    jTable3.setValueAt(null,i,j);
                    counter=0;
                    compMove=0;
                }
            }
        }else if(counter==9){
            JOptionPane.showMessageDialog(null,"Ничья!",null,0);
            
            for(int i=0;i<3;i++){
                for(int j=0;j<3;j++){
                    jTable3.setValueAt(null,i,j);
                    counter=0;
                    compMove=0;
                }
            }
        }
    }
 }
    
    
    //метод для хода пользователя
public void player_move(){  
    boolean playerMove = true;
    boolean player = true;
    if(playerMove){
        playerMove = false;
        int row = jTable3.getSelectedRow();
        int column = jTable3.getSelectedColumn();

        if(jTable3.getValueAt(row, column) == null) {
            if(player){
                jTable3.setValueAt("  X", row, column);

                playerMove = true;
                System.out.println(playerMove);
            }else  {
                player = !player;   
            }
        } else {
            playerMove = false;
            System.out.println("dddd");
            System.out.println(playerMove);
            JOptionPane.showMessageDialog(null, "Ячейка занята",null,0);
        }
    }
        //compMove++;  
  } 
  //Метод ходов компьютера
   public   void comp_move(){
   int x=0;
   int y=0;
   int rowIndex=0;
   int columnIndex=0;
   Random rand = new Random();
   System.out.println(x);
   
   while(x<1){
       System.out.println(x);
       rowIndex= rand.nextInt((2) + 1);
       columnIndex= rand.nextInt((2) + 1);
       //System.out.println(rowIndex+" "+columnIndex);
       //System.out.println(columnIndex);
       String s=""+jTable3.getValueAt(rowIndex, columnIndex);
       //System.out.println(s);
        
            //System.out.println("");
            if(jTable3.getValueAt(rowIndex,columnIndex)== null){
              System.out.println("ffgth");
              jTable3.setValueAt("  O",rowIndex, columnIndex);
              x++; 
            }
        
    }
   counter++;
  
}
 //метод проверки на победу  
 public String checkWin(){
  
  for(int i=0;i<3;i++)
        if((jTable3.getValueAt(i,0)==jTable3.getValueAt(i,1)&&jTable3.getValueAt(i,0)==jTable3.getValueAt(i,2) && jTable3.getValueAt(i,2)!=null)){
            System.out.println("1="+jTable3.getValueAt(i,2));
            return (String)jTable3.getValueAt(i,2);
        }
        else if (((jTable3.getValueAt(0,i)==jTable3.getValueAt(1,i)&&jTable3.getValueAt(0,i)==jTable3.getValueAt(2,i))&&jTable3.getValueAt(2,i)!=null ))
            {System.out.println("2="+jTable3.getValueAt(2,i));
        
        return (String)jTable3.getValueAt(2,i);}
  
        if((jTable3.getValueAt(0,0) == jTable3.getValueAt(1,1) && jTable3.getValueAt(1,1) == jTable3.getValueAt(2,2)  ||
            jTable3.getValueAt(0,2) == jTable3.getValueAt(1,1) && jTable3.getValueAt(1,1) == jTable3.getValueAt(2,0)) &&
            jTable3.getValueAt(1,1) !=null){
            return (String)jTable3.getValueAt(1,1);
        }
        
    System.out.println("3="+jTable3.getValueAt(1,1));
    
    return null;
 }  
 ///////////////////////////////////////////////
 ///////////////////////////////////////////////
 ///////////ПЕРЕСТАВЬ ФИГУРЫ////////////////////
 ///////////////////////////////////////////////
 
 public void StartField(){
    for(int i=1;i<4;i++){
        jTable1.setValueAt(" \u2655", 0,i);
    }
    for(int i=1;i<4;i++){
        jTable1.setValueAt(" \u265f", 2,i);
    }
}
   int x= 0, y= 0;
   
 /*public void getCoordinate(){
        System.out.println(clickCounter+" cl");
        if(clickCounter==1){
          x1=jTable1.getSelectedRow();
          y1=jTable1.getSelectedColumn();
//          System.out.println("x1 "+x1+" "+y1);
        }     
        if(clickCounter==2){
          x2=jTable1.getSelectedRow();
          y2=jTable1.getSelectedColumn();
//          System.out.println("x2 "+x2+" "+y2);
           clickCounter=0;
        }
    
 }
  public void game2(){
  getCoordinate();
  move_figure();
  
  }
  public void move_figure(){
  System.out.println("x1 "+x1+" "+y1);
  System.out.println("x2 "+x2+" "+y2);
  String Value1=(String)jTable1.getValueAt(x1,y1);
  String value2=(String)jTable1.getValueAt(x2,y2);
  System.out.println(Value1);
  jTable1.setValueAt("",x1,y2);
  jTable1.setValueAt(Value1,x2,y2);
 x1=0;
 x2=0;
 y1=0;
 y2=0;
  
  
  
  }
 */
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
